### ISSUE TITLE
e2e tests run only once

### ISSUE THREAD

**Issue by bonomat** [bitbetwin/bitbetwin#58]
e2e should empty database before starting in order to have a clean start

**Comment by holzeis** [comment]
I think we should consider an own database for the tests. wdyt?

**Comment by bonomat** [comment]
sure, sounds reasonable, but still, we have to figure out how to reset the
db before each start

**Comment by holzeis** [comment]
I think this issue is related to #51. We somehow have to deal with dynamic data, like changing phrases, etc.
What do you think of starting the server in a test mode with some additional testing functionalities, like resetting the test-db and a test phrase generator -> Some fixed data on which we can expect on.
